#!/usr/bin/env python3
"""Generate/check native redistribution licenses from the locked Cargo graph.

No network fetching of license overrides: missing upstream texts are reviewed,
pinned by commit/hash, and stored in rust/licenses/sources.json.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent


def render(metadata):
    overrides_root = ROOT / 'rust/licenses'
    overrides = json.loads((overrides_root / 'sources.json').read_text())
    used_overrides = set()
    inventory = []
    texts = {}
    packages = sorted(metadata['packages'], key=lambda p: (p['name'], p['version']))
    for package in packages:
        if (package['source'] is None and
                Path(package['manifest_path']).resolve() == (ROOT / 'rust/Cargo.toml').resolve()):
            continue  # Only our own crate is covered by the root MIT license.
        # Vendored upstream crates still require their original license texts.
        identity = package['name'] + '@' + package['version']
        directory = Path(package['manifest_path']).parent
        files = sorted(f for f in directory.iterdir() if f.is_file() and
                       f.name.lower().startswith(('license', 'copying', 'copyright', 'notice')))
        declared = package.get('license_file')
        if declared:
            declared = directory / declared
            if not declared.is_file():
                raise ValueError(f'{identity}: declared license file missing')
            if declared not in files:
                files.append(declared)
        documents = [(f.name, f.read_bytes()) for f in files]
        if not documents:
            override = overrides.get(identity)
            if override is None:
                raise ValueError(f'{identity}: no license text; reviewed override required')
            vcs_path = directory / '.cargo_vcs_info.json'
            if not vcs_path.is_file() and package['source'] is None:
                vcs_path = directory.parent / (package['name'] + '-vcs-info.json')
            vcs = json.loads(vcs_path.read_text())
            if override['commit'] != vcs['git']['sha1'] or override['license'] != package['license']:
                raise ValueError(f'{identity}: upstream override differs from published package')
            used_overrides.add(identity)
            for entry in override['files']:
                data = (overrides_root / entry['file']).read_bytes()
                if hashlib.sha256(data).hexdigest() != entry['sha256']:
                    raise ValueError(f'{identity}: upstream license hash mismatch')
                documents.append((entry['source'], data))
        refs = []
        for filename, data in documents:
            text = data.decode('utf-8').replace('\r\n', '\n').rstrip() + '\n'
            digest = hashlib.sha256(text.encode()).hexdigest()
            record = texts.setdefault(digest, {'text': text, 'packages': []})
            record['packages'].append(f'{identity}: {filename}')
            refs.append(digest)
        inventory.append(f"{identity} | {package['license']} | " + ', '.join(sorted(set(refs))))
    unused = set(overrides) - used_overrides
    if unused:
        raise ValueError('Unused license overrides: ' + ', '.join(sorted(unused)))
    output = [
        'Native third-party licenses for bletide',
        'Generated by tool/native_licenses.py from rust/Cargo.lock.',
        'Includes all resolved native targets, build and development dependencies.',
        'Declared SPDX expressions are recorded; license texts are included verbatim.',
        'Exact-commit upstream overrides are recorded in rust/licenses/sources.json.',
        'This inventory does not assert that every crate ships on every platform.',
        '', f'Package inventory ({len(inventory)} dependencies)', '', *inventory, '',
    ]
    for digest, record in sorted(texts.items()):
        output.extend(['=' * 72, 'License text SHA-256: ' + digest,
                       *sorted(record['packages']), '', record['text']])
    return '\n'.join(output)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--metadata', type=Path, help='Previously collected locked Cargo metadata')
    parser.add_argument('--output', type=Path, default=ROOT / 'THIRD_PARTY_LICENSES')
    args = parser.parse_args()
    try:
        if args.metadata:
            metadata = json.loads(args.metadata.read_text())
        else:
            result = subprocess.run(['cargo', 'metadata', '--locked', '--all-features',
                                     '--format-version', '1'], cwd=ROOT / 'rust',
                                    check=True, text=True, stdout=subprocess.PIPE)
            metadata = json.loads(result.stdout)
        content = render(metadata)
        if args.check:
            if not args.output.is_file() or args.output.read_text() != content:
                raise ValueError('Native license inventory is stale; run tool/native_licenses.py')
            print('Native redistribution license inventory is current')
        else:
            args.output.write_text(content)
            print('Wrote', args.output.name)
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
